version: '2'
services:
  client:
    build:
      context: jvm/
    volumes:
      - ../project/:/app
    links:
      - server
    environment:
      - JAR_NAME=app/target/client.jar
    restart: on-failure
  server:
    build:
      context: jvm/
    volumes:
      - ../project/:/app
    environment:
      - JAR_NAME=app/target/server.jar
    restart: on-failure
  maven:
    build:
      context: maven/
    volumes:
      - ../project:/app
    restart: on-failure
