version: '2'
services:
  client:
    build:
      context: jvm/
    volumes:
      - ../client/:/app
  server:
    build:
      context: jvm/
    volumes:
      - ../server/:/app
  maven-client:
    build:
      context: maven/
    volumes:
      - ../client:/app
  maven-server:
    build:
      context: maven/
    volumes:
      - ../server:/app
