version: '2'
services:
  client:
    build:
      context: jvm/
    volumes:
      - ../source/:/app
    restart: on-failure
    environment:
      - JAR_NAME=client.jar
    links:
      - server
  server:
    build:
      context: jvm/
    volumes:
      - ../source/:/app
    environment:
      - JAR_NAME=server.jar
    restart: on-failure
  maven:
    build:
      context: maven/
    volumes:
      - ../source:/app
    restart: on-failure
